[build]
  publish = "."
  functions = "netlify/functions"

[functions."imagegen"]
  timeout = 26


[[redirects]]
  from = "/api/claude"
  to = "/.netlify/functions/claude"
  status = 200

[[redirects]]
  from = "/api/market"
  to = "/.netlify/functions/market"
  status = 200

[[redirects]]
  from = "/api/imagegen"
  to = "/.netlify/functions/imagegen"
  status = 200
